# Generated by Django 5.0 on 2024-11-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Municipal', '0003_alter_solicitud_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={},
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='usuario',
        ),
    ]
